openapi: 3.0.0
info:
  version: 1.0.0
  title: Test
paths:
  /parameters/{id}:
    get:
      summary: parameters in various places
      operationId: parameters
      tags: ["request"]
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
          required: false
        - name: q
          in: query
          schema:
            type: string
          required: false
        - name: X-Request-ID
          in: header
          schema:
            type: string
          required: false
        - name: sessionId
          in: cookie
          schema:
            type: string
          required: false
      responses:
        "201":
          description: Null response
        default:
          description: General error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /application_json:
    post:
      summary: request body with application/json
      operationId: applicationJson
      tags: ["request"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                  format: int32
              required:
                - name
                - age
      responses:
        "201":
          description: Null response

  /application_json/components_ref:
    post:
      summary: request body with components ref
      operationId: applicationJsonWithComponentsRef
      tags: ["request"]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SchemaComponent"
      responses:
        "201":
          description: Null response

  /application_json/file_ref:
    post:
      summary: request body with file ref
      operationId: applicationJsonWithFileRef
      tags: ["request"]
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: "./file_object.yaml"
      responses:
        "201":
          description: Null response

  /octet_stream:
    post:
      summary: request body with application/octet-stream
      operationId: octetStream
      tags: ["request"]
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "201":
          description: Null response

  /text_plain:
    post:
      summary: request body with text/plain
      operationId: textPlain
      tags: ["request"]
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
      responses:
        "201":
          description: Null response

  /multipart_form_data:
    post:
      summary: request body with multipart/form-data
      operationId: multipartFormData
      tags: ["request"]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                authority:
                  type: object
                  properties:
                    name:
                      type: string
                    url:
                      type: string
                  required:
                    - name
                    - url
                photo:
                  type: string
                  format: binary
                attachments:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "201":
          description: Null response

  /x_www_form_urlencoded:
    post:
      summary: request body with application/x-www-form-urlencoded
      operationId: xWwwFormUrlencoded
      tags: ["request"]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                type:
                  type: string
                links:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      url:
                        type: string
      responses:
        "201":
          description: Null response

  /mixed:
    post:
      summary: request body with multiple content types
      operationId: mixed
      tags: ["request"]
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
          application/json:
            schema:
              type: object
              properties:
                age:
                  type: integer
                  format: int32
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "201":
          description: Null response

  /dates:
    post:
      summary: request body with dates field
      operationId: dates
      tags: ["request"]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                createdAt:
                  type: string
                  format: date-time
                holiday:
                  type: string
                  format: date
      responses:
        "201":
          description: Null response

  /responses/text_plain:
    get:
      summary: string response
      operationId: textPlainResponse
      tags: ["response"]
      responses:
        "200":
          description: string response
          content:
            text/plain:
              schema:
                type: string

  /responses/application_json/inline:
    get:
      summary: object response
      operationId: applicationJsonInlineResponse
      tags: ["response"]
      responses:
        "200":
          description: inline object response
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  age:
                    type: integer
                    format: int32

  /responses/application_json/components_ref:
    get:
      summary: object response
      operationId: applicationJsonComponentsRefResponse
      tags: ["response"]
      responses:
        "200":
          description: components response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SchemaComponent"

  /responses/application_json/file_ref:
    get:
      summary: object response
      operationId: applicationJsonFileRefResponse
      tags: ["response"]
      responses:
        "200":
          description: object response
          content:
            application/json:
              schema:
                $ref: "./file_object.yaml"

components:
  schemas:
    SchemaComponent:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
